[package]
name = "melkon_td"
version = "0.1.0"
authors = ["Attila Szenczi <szenczi.attila90@gmail.com>"]
edition = "2021"

[dependencies]
if_chain = "1.0.0"
utils = {path = "utils"}
sfml = "0.16.0"
generational-arena = "0.2.8"